WS-5350 Updated Link and Pagination Selector Information
webscraperio/web-scraper-documentation pull request #42
Opened 2024-02-15 08:28 UTC by karinaMeldere

Added another link type to "Link selector" page and reformatted the "Pagination selector" page.

2024-02-15 08:44 UTC, einarsozols approved these changes

2024-02-15 09:11 UTC, ivarsweb approved these changes

2024-02-15 09:38 UTC, martinsbalodis commented
waiting for Ivars second review

2024-02-15 10:13 UTC, ivarsweb requested changes

2024-02-15 10:13 UTC, ivarsweb commented on docs/Selectors/Link selector.md
> +The Link Selector is only recognizing <a> elements using the point-and-click interface to be a selector,
All Link Selector types except for 'Link from any script' only allow selecting <a> elements using the point-and-click interface
although other elements can be selected by manually entering the CSS selector value as a selector.

The 'Link from any script' type allows any element to be selected using the point-and-click interface.

2024-04-08 10:41 UTC, ivarsweb approved these changes

2024-04-08 10:48 UTC, martinsbalodis approved these changes

2024-04-08 10:48 UTC, merged